### ISSUE TITLE
Add expedition launch and end dates

### ISSUE THREAD

**Issue by AleksiKuj** [corquaid/international-space-station-APIs#12]
Thanks for the nice API! Would it be possible to add the start date of current expedition and the expected end date to People In Space API? I think it could be useful.

**Comment by corquaid** [comment]
Thanks for the star and suggestion! If you want to go ahead and raise a PR with these fields added you're more than welcome, if not, I'll get to it on the next update in a couple of weeks for the next Progress launch 👍
